### ISSUE TITLE
Put app on Azure

### ISSUE THREAD

**Issue by jhachtel** [jhachtel/AMIS3610-Group-Project#24]
App needs to live on Azure. Database is already there, but we need to fix the identity issues to use it properly.

**Comment by Demerti** [comment]
Its in azure currently correct? If so close this issue @jhachtel

**Comment by jhachtel** [comment]
Waiting for Azure to finish setting up the app service

**Comment by jhachtel** [comment]
Working issue #90

**Comment by jhachtel** [comment]
Back at it

**Comment by jhachtel** [comment]
@AlexTetzloff - Please be careful - I am in the process of loading the app to Azure. Any breakage or changes might prevent it right now.

**Comment by jhachtel** [comment]
Index and Error pages set to index.html

**Comment by jhachtel** [comment]
https://amis3610offthetrail.z19.web.core.windows.net/dashboard

Done

**Comment by jhachtel** [comment]
For later: https://code.visualstudio.com/tutorials/static-website/code-change

Code change workflow...
